// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/mi8.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type News struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,6,opt,name=country,proto3" json:"country,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *News) Reset() {
	*x = News{}
	mi := &file_proto_mi8_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *News) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*News) ProtoMessage() {}

func (x *News) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mi8_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use News.ProtoReflect.Descriptor instead.
func (*News) Descriptor() ([]byte, []int) {
	return file_proto_mi8_proto_rawDescGZIP(), []int{0}
}

func (x *News) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *News) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *News) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *News) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *News) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *News) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

type GetLatestNewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestNewsRequest) Reset() {
	*x = GetLatestNewsRequest{}
	mi := &file_proto_mi8_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestNewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestNewsRequest) ProtoMessage() {}

func (x *GetLatestNewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mi8_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestNewsRequest.ProtoReflect.Descriptor instead.
func (*GetLatestNewsRequest) Descriptor() ([]byte, []int) {
	return file_proto_mi8_proto_rawDescGZIP(), []int{1}
}

func (x *GetLatestNewsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetLatestNewsInCityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLatestNewsInCityRequest) Reset() {
	*x = GetLatestNewsInCityRequest{}
	mi := &file_proto_mi8_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLatestNewsInCityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLatestNewsInCityRequest) ProtoMessage() {}

func (x *GetLatestNewsInCityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mi8_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLatestNewsInCityRequest.ProtoReflect.Descriptor instead.
func (*GetLatestNewsInCityRequest) Descriptor() ([]byte, []int) {
	return file_proto_mi8_proto_rawDescGZIP(), []int{2}
}

func (x *GetLatestNewsInCityRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *GetLatestNewsInCityRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type NewsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	News          []*News                `protobuf:"bytes,1,rep,name=news,proto3" json:"news,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewsList) Reset() {
	*x = NewsList{}
	mi := &file_proto_mi8_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewsList) ProtoMessage() {}

func (x *NewsList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mi8_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewsList.ProtoReflect.Descriptor instead.
func (*NewsList) Descriptor() ([]byte, []int) {
	return file_proto_mi8_proto_rawDescGZIP(), []int{3}
}

func (x *NewsList) GetNews() []*News {
	if x != nil {
		return x.News
	}
	return nil
}

type GetCityScoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCityScoreRequest) Reset() {
	*x = GetCityScoreRequest{}
	mi := &file_proto_mi8_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCityScoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCityScoreRequest) ProtoMessage() {}

func (x *GetCityScoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mi8_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCityScoreRequest.ProtoReflect.Descriptor instead.
func (*GetCityScoreRequest) Descriptor() ([]byte, []int) {
	return file_proto_mi8_proto_rawDescGZIP(), []int{4}
}

func (x *GetCityScoreRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

type GetTopCitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopCitiesRequest) Reset() {
	*x = GetTopCitiesRequest{}
	mi := &file_proto_mi8_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopCitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopCitiesRequest) ProtoMessage() {}

func (x *GetTopCitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mi8_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopCitiesRequest.ProtoReflect.Descriptor instead.
func (*GetTopCitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_mi8_proto_rawDescGZIP(), []int{5}
}

func (x *GetTopCitiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CityScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	City          string                 `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	QualityOfLife int32                  `protobuf:"varint,3,opt,name=quality_of_life,json=qualityOfLife,proto3" json:"quality_of_life,omitempty"`
	Safety        int32                  `protobuf:"varint,4,opt,name=safety,proto3" json:"safety,omitempty"`
	Economy       int32                  `protobuf:"varint,5,opt,name=economy,proto3" json:"economy,omitempty"`
	Culture       int32                  `protobuf:"varint,6,opt,name=culture,proto3" json:"culture,omitempty"`
	LastUpdated   string                 `protobuf:"bytes,7,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CityScore) Reset() {
	*x = CityScore{}
	mi := &file_proto_mi8_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityScore) ProtoMessage() {}

func (x *CityScore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mi8_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityScore.ProtoReflect.Descriptor instead.
func (*CityScore) Descriptor() ([]byte, []int) {
	return file_proto_mi8_proto_rawDescGZIP(), []int{6}
}

func (x *CityScore) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CityScore) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CityScore) GetQualityOfLife() int32 {
	if x != nil {
		return x.QualityOfLife
	}
	return 0
}

func (x *CityScore) GetSafety() int32 {
	if x != nil {
		return x.Safety
	}
	return 0
}

func (x *CityScore) GetEconomy() int32 {
	if x != nil {
		return x.Economy
	}
	return 0
}

func (x *CityScore) GetCulture() int32 {
	if x != nil {
		return x.Culture
	}
	return 0
}

func (x *CityScore) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

type CityScoreList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scores        []*CityScore           `protobuf:"bytes,1,rep,name=scores,proto3" json:"scores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CityScoreList) Reset() {
	*x = CityScoreList{}
	mi := &file_proto_mi8_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CityScoreList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityScoreList) ProtoMessage() {}

func (x *CityScoreList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_mi8_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityScoreList.ProtoReflect.Descriptor instead.
func (*CityScoreList) Descriptor() ([]byte, []int) {
	return file_proto_mi8_proto_rawDescGZIP(), []int{7}
}

func (x *CityScoreList) GetScores() []*CityScore {
	if x != nil {
		return x.Scores
	}
	return nil
}

var File_proto_mi8_proto protoreflect.FileDescriptor

const file_proto_mi8_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/mi8.proto\x12\x03mi8\x1a\x1bgoogle/protobuf/empty.proto\"\x88\x01\n" +
	"\x04News\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x06 \x01(\tR\acountry\",\n" +
	"\x14GetLatestNewsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"F\n" +
	"\x1aGetLatestNewsInCityRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\")\n" +
	"\bNewsList\x12\x1d\n" +
	"\x04news\x18\x01 \x03(\v2\t.mi8.NewsR\x04news\")\n" +
	"\x13GetCityScoreRequest\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\"+\n" +
	"\x13GetTopCitiesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\xd0\x01\n" +
	"\tCityScore\x12\x12\n" +
	"\x04city\x18\x01 \x01(\tR\x04city\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12&\n" +
	"\x0fquality_of_life\x18\x03 \x01(\x05R\rqualityOfLife\x12\x16\n" +
	"\x06safety\x18\x04 \x01(\x05R\x06safety\x12\x18\n" +
	"\aeconomy\x18\x05 \x01(\x05R\aeconomy\x12\x18\n" +
	"\aculture\x18\x06 \x01(\x05R\aculture\x12!\n" +
	"\flast_updated\x18\a \x01(\tR\vlastUpdated\"7\n" +
	"\rCityScoreList\x12&\n" +
	"\x06scores\x18\x01 \x03(\v2\x0e.mi8.CityScoreR\x06scores2\xc1\x02\n" +
	"\n" +
	"MI8Service\x12;\n" +
	"\rGetLatestNews\x12\x19.mi8.GetLatestNewsRequest\x1a\r.mi8.NewsList\"\x00\x12G\n" +
	"\x13GetLatestNewsInCity\x12\x1f.mi8.GetLatestNewsInCityRequest\x1a\r.mi8.NewsList\"\x00\x121\n" +
	"\n" +
	"CreateNews\x12\t.mi8.News\x1a\x16.google.protobuf.Empty\"\x00\x12:\n" +
	"\fGetCityScore\x12\x18.mi8.GetCityScoreRequest\x1a\x0e.mi8.CityScore\"\x00\x12>\n" +
	"\fGetTopCities\x12\x18.mi8.GetTopCitiesRequest\x1a\x12.mi8.CityScoreList\"\x00B\vZ\tmi8/protob\x06proto3"

var (
	file_proto_mi8_proto_rawDescOnce sync.Once
	file_proto_mi8_proto_rawDescData []byte
)

func file_proto_mi8_proto_rawDescGZIP() []byte {
	file_proto_mi8_proto_rawDescOnce.Do(func() {
		file_proto_mi8_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_mi8_proto_rawDesc), len(file_proto_mi8_proto_rawDesc)))
	})
	return file_proto_mi8_proto_rawDescData
}

var file_proto_mi8_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_mi8_proto_goTypes = []any{
	(*News)(nil),                       // 0: mi8.News
	(*GetLatestNewsRequest)(nil),       // 1: mi8.GetLatestNewsRequest
	(*GetLatestNewsInCityRequest)(nil), // 2: mi8.GetLatestNewsInCityRequest
	(*NewsList)(nil),                   // 3: mi8.NewsList
	(*GetCityScoreRequest)(nil),        // 4: mi8.GetCityScoreRequest
	(*GetTopCitiesRequest)(nil),        // 5: mi8.GetTopCitiesRequest
	(*CityScore)(nil),                  // 6: mi8.CityScore
	(*CityScoreList)(nil),              // 7: mi8.CityScoreList
	(*emptypb.Empty)(nil),              // 8: google.protobuf.Empty
}
var file_proto_mi8_proto_depIdxs = []int32{
	0, // 0: mi8.NewsList.news:type_name -> mi8.News
	6, // 1: mi8.CityScoreList.scores:type_name -> mi8.CityScore
	1, // 2: mi8.MI8Service.GetLatestNews:input_type -> mi8.GetLatestNewsRequest
	2, // 3: mi8.MI8Service.GetLatestNewsInCity:input_type -> mi8.GetLatestNewsInCityRequest
	0, // 4: mi8.MI8Service.CreateNews:input_type -> mi8.News
	4, // 5: mi8.MI8Service.GetCityScore:input_type -> mi8.GetCityScoreRequest
	5, // 6: mi8.MI8Service.GetTopCities:input_type -> mi8.GetTopCitiesRequest
	3, // 7: mi8.MI8Service.GetLatestNews:output_type -> mi8.NewsList
	3, // 8: mi8.MI8Service.GetLatestNewsInCity:output_type -> mi8.NewsList
	8, // 9: mi8.MI8Service.CreateNews:output_type -> google.protobuf.Empty
	6, // 10: mi8.MI8Service.GetCityScore:output_type -> mi8.CityScore
	7, // 11: mi8.MI8Service.GetTopCities:output_type -> mi8.CityScoreList
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_mi8_proto_init() }
func file_proto_mi8_proto_init() {
	if File_proto_mi8_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_mi8_proto_rawDesc), len(file_proto_mi8_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_mi8_proto_goTypes,
		DependencyIndexes: file_proto_mi8_proto_depIdxs,
		MessageInfos:      file_proto_mi8_proto_msgTypes,
	}.Build()
	File_proto_mi8_proto = out.File
	file_proto_mi8_proto_goTypes = nil
	file_proto_mi8_proto_depIdxs = nil
}
