// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/mi8.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MI8Service_GetLatestNews_FullMethodName       = "/mi8.MI8Service/GetLatestNews"
	MI8Service_GetLatestNewsInCity_FullMethodName = "/mi8.MI8Service/GetLatestNewsInCity"
	MI8Service_CreateNews_FullMethodName          = "/mi8.MI8Service/CreateNews"
)

// MI8ServiceClient is the client API for MI8Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The MI8 service definition.
type MI8ServiceClient interface {
	// Get latest news
	GetLatestNews(ctx context.Context, in *GetLatestNewsRequest, opts ...grpc.CallOption) (*NewsList, error)
	// Get latest news by city
	GetLatestNewsInCity(ctx context.Context, in *GetLatestNewsInCityRequest, opts ...grpc.CallOption) (*NewsList, error)
	// Create news
	CreateNews(ctx context.Context, in *News, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type mI8ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMI8ServiceClient(cc grpc.ClientConnInterface) MI8ServiceClient {
	return &mI8ServiceClient{cc}
}

func (c *mI8ServiceClient) GetLatestNews(ctx context.Context, in *GetLatestNewsRequest, opts ...grpc.CallOption) (*NewsList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewsList)
	err := c.cc.Invoke(ctx, MI8Service_GetLatestNews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mI8ServiceClient) GetLatestNewsInCity(ctx context.Context, in *GetLatestNewsInCityRequest, opts ...grpc.CallOption) (*NewsList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewsList)
	err := c.cc.Invoke(ctx, MI8Service_GetLatestNewsInCity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mI8ServiceClient) CreateNews(ctx context.Context, in *News, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MI8Service_CreateNews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MI8ServiceServer is the server API for MI8Service service.
// All implementations must embed UnimplementedMI8ServiceServer
// for forward compatibility.
//
// The MI8 service definition.
type MI8ServiceServer interface {
	// Get latest news
	GetLatestNews(context.Context, *GetLatestNewsRequest) (*NewsList, error)
	// Get latest news by city
	GetLatestNewsInCity(context.Context, *GetLatestNewsInCityRequest) (*NewsList, error)
	// Create news
	CreateNews(context.Context, *News) (*emptypb.Empty, error)
	mustEmbedUnimplementedMI8ServiceServer()
}

// UnimplementedMI8ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMI8ServiceServer struct{}

func (UnimplementedMI8ServiceServer) GetLatestNews(context.Context, *GetLatestNewsRequest) (*NewsList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestNews not implemented")
}
func (UnimplementedMI8ServiceServer) GetLatestNewsInCity(context.Context, *GetLatestNewsInCityRequest) (*NewsList, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestNewsInCity not implemented")
}
func (UnimplementedMI8ServiceServer) CreateNews(context.Context, *News) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateNews not implemented")
}
func (UnimplementedMI8ServiceServer) mustEmbedUnimplementedMI8ServiceServer() {}
func (UnimplementedMI8ServiceServer) testEmbeddedByValue()                    {}

// UnsafeMI8ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MI8ServiceServer will
// result in compilation errors.
type UnsafeMI8ServiceServer interface {
	mustEmbedUnimplementedMI8ServiceServer()
}

func RegisterMI8ServiceServer(s grpc.ServiceRegistrar, srv MI8ServiceServer) {
	// If the following call panics, it indicates UnimplementedMI8ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MI8Service_ServiceDesc, srv)
}

func _MI8Service_GetLatestNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestNewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MI8ServiceServer).GetLatestNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MI8Service_GetLatestNews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MI8ServiceServer).GetLatestNews(ctx, req.(*GetLatestNewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MI8Service_GetLatestNewsInCity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestNewsInCityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MI8ServiceServer).GetLatestNewsInCity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MI8Service_GetLatestNewsInCity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MI8ServiceServer).GetLatestNewsInCity(ctx, req.(*GetLatestNewsInCityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MI8Service_CreateNews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(News)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MI8ServiceServer).CreateNews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MI8Service_CreateNews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MI8ServiceServer).CreateNews(ctx, req.(*News))
	}
	return interceptor(ctx, in, info, handler)
}

// MI8Service_ServiceDesc is the grpc.ServiceDesc for MI8Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MI8Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mi8.MI8Service",
	HandlerType: (*MI8ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestNews",
			Handler:    _MI8Service_GetLatestNews_Handler,
		},
		{
			MethodName: "GetLatestNewsInCity",
			Handler:    _MI8Service_GetLatestNewsInCity_Handler,
		},
		{
			MethodName: "CreateNews",
			Handler:    _MI8Service_CreateNews_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mi8.proto",
}
